project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: experience.qmd
        text: Experience
      - href: education.qmd
        text: Education
  sidebar:
    style: docked
    logo: bio-pic.jpg
    contents:
      - text: "Alec Bodolay"
      - text: "USC | UCSB | SMC"
      - icon: envelope-fill
        text: "&nbsp; Email"
        href: "mailto:bodolay@usc.edu"
      - icon: linkedin
        href: https://www.linkedin.com/in/filipr/
        text: "&nbsp; LinkedIn"
      - text: "{{< ai google-scholar >}} &thinsp; &nbsp; Google Scholar"
        href: https://scholar.google.fr/citations?user=bodolayalec
      - icon: github
        text: "&nbsp; GitHub"
        href: https://github.com/alecbodolay/
      - text: "{{< ai orcid >}} &nbsp; ORCID"
        href: https://orcid.org/0009-0006-9030-4711


format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: true
    fontawesome: true
    code-tools: false
    grid:
      sidebar-width: 400px
      body-width: 800px;
      margin-width: 200px
 


editor: visual

